apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/build-enable-automatic-updates: 'false'
    run.googleapis.com/build-id: 8d1fe2e9-0fa9-4051-bf6d-15ad8adbd480
    run.googleapis.com/build-image-uri: europe-north1-docker.pkg.dev/servfix-test/cloud-run-source-deploy/servfix-app
    run.googleapis.com/build-name: projects/561535995501/locations/europe-north1/builds/8d1fe2e9-0fa9-4051-bf6d-15ad8adbd480
    run.googleapis.com/build-source-location: gs://run-sources-servfix-test-europe-north1/services/servfix-app/1762992218.285007-6f38220de7564a76805626c0fe223e6c.zip#1762992158186897
    run.googleapis.com/client-name: gcloud
    run.googleapis.com/client-version: 532.0.0
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    run.googleapis.com/operation-id: f7220000-d298-4384-ae15-087843c26855
    run.googleapis.com/urls: '["https://servfix-app-561535995501.europe-north1.run.app","https://servfix-app-3e7dc7jgxa-lz.a.run.app"]'
    serving.knative.dev/creator: servfixadm@gmail.com
    serving.knative.dev/lastModifier: servfixadm@gmail.com
  creationTimestamp: '2025-09-14T21:38:04.235899Z'
  generation: 54
  labels:
    cloud.googleapis.com/location: europe-north1
  name: servfix-app
  namespace: '561535995501'
  resourceVersion: AAZDbu/H5jE
  selfLink: /apis/serving.knative.dev/v1/namespaces/561535995501/services/servfix-app
  uid: c8f49842-bf4f-47f4-ad6a-1719ba942c59
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '5'
        run.googleapis.com/client-name: gcloud
        run.googleapis.com/client-version: 532.0.0
        run.googleapis.com/cloudsql-instances: servfix-test:europe-north1:servfix-test-db
        run.googleapis.com/startup-cpu-boost: 'true'
      labels:
        client.knative.dev/nonce: pmouamgtee
        run.googleapis.com/startupProbeType: Default
    spec:
      containerConcurrency: 80
      containers:
      - env:
        - name: NODE_ENV
          value: production
        - name: CLOUD_SQL_CONNECTION_NAME
          value: servfix-test:europe-north1:servfix-test-db
        - name: DB_USER
          value: postgres
        - name: DB_NAME
          value: servfix_admin
        - name: DEFAULT_TENANT_ID
          value: airtech
        - name: GCS_BUCKET_NAME
          value: servfix-files-test
        - name: GOOGLE_CLOUD_PROJECT_ID
          value: servfix-test
        - name: BASE_URL
          value: https://api-test.tripletex.tech/v2
        - name: SMTP_HOST
          value: smtp.gmail.com
        - name: SMTP_PORT
          value: '587'
        - name: SMTP_USER
          value: servfixadm@gmail.com
        - name: SMTP_FROM
          value: servfixadm@gmail.com
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: latest
              name: db-password
        - name: SESSION_SECRET
          valueFrom:
            secretKeyRef:
              key: latest
              name: session-secret
        - name: CONSUMER_TOKEN
          valueFrom:
            secretKeyRef:
              key: latest
              name: tripletex-consumer-token
        - name: EMPLOYEE_TOKEN
          valueFrom:
            secretKeyRef:
              key: latest
              name: tripletex-employee-token
        - name: SMTP_PASS
          valueFrom:
            secretKeyRef:
              key: latest
              name: smtp-password
        - name: SECRETS_ACCESS_GRANTED
          value: 'true'
        image: europe-north1-docker.pkg.dev/servfix-test/cloud-run-source-deploy/servfix-app@sha256:1043e2cf3e8a12b80b136cc0230d64cad53392d17c713ac7b6e7ed235c86493c
        ports:
        - containerPort: 8080
          name: http1
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
        startupProbe:
          failureThreshold: 1
          periodSeconds: 240
          tcpSocket:
            port: 8080
          timeoutSeconds: 240
      serviceAccountName: 561535995501-compute@developer.gserviceaccount.com
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100
status:
  address:
    url: https://servfix-app-3e7dc7jgxa-lz.a.run.app
  conditions:
  - lastTransitionTime: '2025-11-13T00:26:48.582705Z'
    status: 'True'
    type: Ready
  - lastTransitionTime: '2025-11-13T00:26:40.895858Z'
    status: 'True'
    type: ConfigurationsReady
  - lastTransitionTime: '2025-11-13T00:26:48.550703Z'
    status: 'True'
    type: RoutesReady
  latestCreatedRevisionName: servfix-app-00054-rtm
  latestReadyRevisionName: servfix-app-00054-rtm
  observedGeneration: 54
  traffic:
  - latestRevision: true
    percent: 100
    revisionName: servfix-app-00054-rtm
  url: https://servfix-app-3e7dc7jgxa-lz.a.run.app
