apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/build-enable-automatic-updates: 'false'
    run.googleapis.com/build-id: dc6b0487-f00e-41a5-9e50-b99d20c6be74
    run.googleapis.com/build-image-uri: europe-north1-docker.pkg.dev/servfix-production/cloud-run-source-deploy/servfix-app
    run.googleapis.com/build-name: projects/471345128928/locations/europe-north1/builds/dc6b0487-f00e-41a5-9e50-b99d20c6be74
    run.googleapis.com/build-source-location: gs://run-sources-servfix-production-europe-north1/services/servfix-app/1754307509.253204-618f48a7f18043e38a1fae795245fe11.zip#1754307507771318
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    run.googleapis.com/urls: '["https://servfix-app-471345128928.europe-north1.run.app","https://servfix-app-eufsbr5tvq-lz.a.run.app"]'
  labels:
    cloud.googleapis.com/location: europe-north1
  name: servfix-app
  namespace: '471345128928'
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '10'
        autoscaling.knative.dev/minScale: '1'
        run.googleapis.com/client-name: gcloud
        run.googleapis.com/client-version: 531.0.0
        run.googleapis.com/cloudsql-instances: servfix-production:europe-north1:servfix-db
        run.googleapis.com/startup-cpu-boost: 'true'
      labels:
        client.knative.dev/nonce: rcwkgsmniy
        run.googleapis.com/startupProbeType: Default
    spec:
      containerConcurrency: 80
      containers:
      - env:
        - name: NODE_ENV
          value: production
        - name: CLOUD_SQL_CONNECTION_NAME
          value: servfix-production:europe-north1:servfix-db
        - name: DB_USER
          value: postgres
        - name: GCS_BUCKET_NAME
          value: servfix-files
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: latest
              name: db-password
        - name: SESSION_SECRET
          valueFrom:
            secretKeyRef:
              key: latest
              name: session-secret
        image: europe-north1-docker.pkg.dev/servfix-production/cloud-run-source-deploy/servfix-app@sha256:cdcfe880e59104066450ac52cfe55ef517731ed3e47202f3a6a10e6a61da9359
        ports:
        - containerPort: 8080
          name: http1
        resources:
          limits:
            cpu: 1000m
            memory: 2Gi
        startupProbe:
          failureThreshold: 1
          periodSeconds: 240
          tcpSocket:
            port: 8080
          timeoutSeconds: 240
      serviceAccountName: 471345128928-compute@developer.gserviceaccount.com
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100
